"""Generate the Phase 1 export-readiness and ATen operator report."""

import argparse
from pathlib import Path
from typing import Dict, Tuple

import torch

from analysis import collect_aten_operators, trace_inference_core, verify_trace_parity
from pipeline import create_deterministic_model


DEFAULT_SHAPES = ((1, 3, 16, 24), (1, 3, 17, 21), (2, 3, 32, 40))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("docs/EXPORT_READINESS.md"))
    return parser.parse_args()


def render_report(operators: Dict[str, int], parity: Dict[Tuple[int, int, int, int], float]) -> str:
    operator_rows = "\n".join(f"| `{name}` | {count} |" for name, count in operators.items())
    parity_rows = "\n".join(
        f"| `{shape}` | `{(shape[0], 3, shape[2] * 2, shape[3] * 2)}` | {difference:.8g} |"
        for shape, difference in parity.items()
    )
    public_export = hasattr(torch, "export")
    return f"""# Export Readiness Report

Generated by `python -m tools.inspect_export_readiness` on PyTorch `{torch.__version__}`.

## Scope

This is a Phase 1 preflight, not an ExecuTorch export or backend compatibility claim. The installed PyTorch exposes public `torch.export`: **{public_export}**. The report uses a frozen TorchScript trace of the tensor-only `SpatialSR2x.network` core to expose its local ATen graph.

Python input guards in `SpatialSR2x.forward` are intentionally outside the traced core. The eventual application/runtime boundary must validate NCHW, RGB, dtype, and supported dimensions before invoking an exported program.

## Inference Graph

```text
float32 NCHW RGB
  -> convolution 3 -> 16, kernel 3x3, stride 1, padding 1
  -> ReLU
  -> convolution 16 -> 12, kernel 3x3, stride 1, padding 1
  -> PixelShuffle(scale=2)
  -> float32 NCHW RGB at 2x height and width
```

## ATen Operator Inventory

| Operator | Count |
| --- | ---: |
{operator_rows}

This inventory reflects PyTorch 2.0 TorchScript lowering. Phase 2 must regenerate the operator list from the selected `torch.export`/ExecuTorch graph because names and decompositions may differ.

## Shape and Numerical Preflight

| Input shape | Output shape | Maximum eager/trace absolute difference |
| --- | --- | ---: |
{parity_rows}

Observed traces accept the tested batch and spatial-size variations. This does not establish a formal dynamic-shape contract. Phase 2 must explicitly define and test dynamic dimensions in the supported export API.

## Deployment Risks to Verify

1. `aten::pixel_shuffle` support, decomposition, and QNN delegation are unverified and are the primary operator risk.
2. `aten::_convolution` is expected to lower differently in modern export; backend support must be checked on the actual exported graph.
3. Python validation is not preserved in the trace and must remain at the host/runtime boundary.
4. Only float32 CPU execution is validated. FP16/INT8 and device execution remain later phases.
5. No `.pte`, QNN context binary, or mobile artifact is produced by this task.

## Phase 2 Gate

Before ExecuTorch work, select a mutually supported PyTorch/ExecuTorch version pair, recreate the environment, export with the supported public API, compare outputs, inspect unsupported/delegated partitions, and revisit PixelShuffle only if evidence shows a compatibility or performance problem.
"""


def main() -> None:
    args = parse_args()
    model = create_deterministic_model()
    example = torch.rand(DEFAULT_SHAPES[0], generator=torch.Generator().manual_seed(20260815))
    traced = trace_inference_core(model, example)
    operators = collect_aten_operators(traced)
    parity = verify_trace_parity(model, traced, DEFAULT_SHAPES)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_report(operators, parity), encoding="utf-8")
    print(f"Report: {args.output}")
    print(f"Operators: {operators}")
    print(f"Maximum absolute difference: {max(parity.values()):.8g}")


if __name__ == "__main__":
    main()
